version: "3.9"

networks:
  build_network:

services:

  nginx:
    image: nginx:stable-alpine

    networks:
      - build_network

    ports:
      - "80:80"
  
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
  
    depends_on:
      - app-build

  app-dev:
    container_name: app-dev

    volumes:
      - ./app:/app
      - /app/node_modules

    build:
      context: ./app
      dockerfile: Dockerfile
      target: development

    ports:
      - "5173:5173"

    environment:
      NODE_ENV: development

  app-build:
    container_name: app-build

    build:
      context: ./app
      dockerfile: Dockerfile
      target: production

    networks:
      - build_network

    environment:
      NODE_ENV: production